AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-Tier Architecture
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 
      SecurityGroupIds: []
      KeyName: my-key
