AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline (Free Tier Friendly)
Resources:
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::123456789012:role/CodePipelineRole
      Stages: []
